[project]
name = "python-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.2"
dependencies = [
    "duckdb==1.5.0",
    "geojson-pydantic>=2.1.2",
    "jupyter>=1.1.1",
    "polars==1.33.1",
    "pyarrow>=25.0.1",
    "pydantic==2.12.5",
    "shapely>=2.1.2",
]
